Experiment with regions
Fails with:

$ mvn integration-test -pl google-cloud-storage -Plive \
    -Dtest.google-cloud-storage.identity="${JCLOUDS_IDENTITY}" \
    -Dtest.google-cloud-storage.credential="${JCLOUDS_CREDENTIAL}" \
    -Dtest.google-cloud-storage.project-number="${JCLOUDS_PROJECT_NUMBER}" \
    -Dtest=GCSContainerLiveTest#testPublicAccessInNonDefaultLocation \
    -Dtest.blobstore.container-count=1
...
testPublicAccessInNonDefaultLocation(org.jclouds.googlecloudstorage.blobstore.integration.GCSContainerLiveTest)  Time elapsed: 23.369 sec  <<< FAILURE!
java.lang.AssertionError: blob gaul-blobstore-336316095157997230, in location {scope=REGION, id=ASIA, description=ASIA, parent=google-cloud-storage} instead of {scope=REGION, id=US, description=US, parent=google-cloud-storage}
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest$6.run(BaseBlobStoreIntegrationTest.java:387)
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:235)
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAware(BaseBlobStoreIntegrationTest.java:248)
        at org.jclouds.blobstore.integration.internal.BaseBlobStoreIntegrationTest.assertConsistencyAwareContainerInLocation(BaseBlobStoreIntegrationTest.java:374)
        at org.jclouds.blobstore.integration.internal.BaseContainerLiveTest.runCreateContainerInLocation(BaseContainerLiveTest.java:128)
        at org.jclouds.blobstore.integration.internal.BaseContainerLiveTest.testPublicAccessInNonDefaultLocation(BaseContainerLiveTest.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
        at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)